# Generated by Django 2.2.12 on 2020-04-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_auto_20200426_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/docs/'),
        ),
    ]
