# Generated by Django 2.2.12 on 2020-04-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_auto_20200426_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
