# Generated by Django 3.0.4 on 2020-04-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talking_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
    ]
