# Generated by Django 3.0.4 on 2020-04-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talking_bot', '0002_remove_images_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
