# Generated by Django 3.0.5 on 2020-04-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talking_bot', '0003_images_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
